version: '3'

services:
  jenkins:
    image: 'jenkins/jenkins'
    ports:
      - '8080:8080'
    volumes:
      - './jenkins:/var/jenkins_home'
    deploy:
      restart_policy:
        condition: always
    