node {
  stage('Git') {
    git branch: "master", url: "https://github.com/jenkins-docs/simple-java-maven-app"
  }
  stage('Sonar') {
    withSonarQubeEnv('sonar') {
      sh "'${MVN}' -f pom.xml clean package sonar:sonar"+
      " -Dsonar.login=admin"+
      " -Dsonar.password=suasenha"+
      " -Dsonar.projectKey=BecaDevOps:master"

    }
  }
}