pipeline {
    agent any
    stages {
        stage("checkout:git") {
            steps {
                git branch: "master", url: "https://github.com/jenkins-docs/simple-java-maven-app"
            }
        }

 

        stage("Build:Maven") {     
            steps {
                sh '$MVN -B -DskipTests clean package' 
            }
        }
        stage("Analise:Sonar") {
            steps {
                sh '$MVN sonar:sonar \
                -Dsonar.projectKey=BecaDevOps:master \
                -Dsonar.host.url=http://10.128.0.37:9000 \
                -Dsonar.login=6565010b79f4dc8c76bc1037514a638dd1c04478'
            }
        }
    }
}

